### ISSUE TITLE
Allow for "noun" to stand in for "nouns" and so on

### ISSUE THREAD

**Issue by bitfilms** [mrmaxguns/wonderwordsmodule#9]

**Comment by bitfilms** [comment]
I'm a brand new wonderwords user but in my first attempt to generate a random noun I got the absolute funniest error.

`from wonderwords import RandomWord

rw = RandomWord()

rw.word( include_parts_of_speech=["noun"],word_max_length=6)`

Gave me this priceless error message:

> ValueError: noun is an invalid part of speech

Which of course isn't true in the English sense. A noun is a valid part of speech! Of course I changed my code to "nouns" in my list but still, I think having "nouns" and "noun" both work would avoid this wonderful error message in the future.

**Comment by mrmaxguns** [comment]
Thank you for opening an issue. I agree that there should be an option to add the part of speech as singular. Due to backwards compatibility, both options will be available until Wonderwords `3`. I'll work to implement this fix as soon as possible.

**Comment by bitfilms** [comment]
Terrific! Thank you!

**Comment by mrmaxguns** [comment]
This issue was fixed. Note that this will not take affect until I publish `V2.1`. There's also now a way to add custom categories!

```
from wonderwords import RandomWord, Defaults

w = RandomWord(verb=Defaults.VERBS, name=["Bob", "Jill", "Max"])
w.word(include_categories=["name"]) # Note that I added the include_categories argument
    # which does the exact same thing as include_parts_of_speech, but the name is more
    # fitting.
    # 'Jill'
w.word() # 'appraise'
```

I'll close this issue once I write tests and document the change.

**Comment by mrmaxguns** [comment]
- [X] Tests
- [ ] Documentation

**Comment by mrmaxguns** [comment]
Issue resolved. The new version of Wonderwords fixes this issue. Install with `pip install wonderwords==2.2.0`.

**Comment by bitfilms** [comment]
Terrific! Thank you!
